const FETCH_GAMES = "HOME/FETCH_GAMES";
const CREATE_GAME = "HOME/CREATE_GAME";
const DELETE_GAME = "HOME/DELETE_GAME";
const RATE_GAME = "HOME/RATE_GAME";
const FILTER_GAMES = "HOME/FILTER_GAMES";
const SORT_GAMES = "HOME/SORT_GAMES";

export default {
    FETCH_GAMES,
    CREATE_GAME,
    DELETE_GAME,
    RATE_GAME,
    FILTER_GAMES,
    SORT_GAMES
};
